### ISSUE TITLE
Comm 클래스 개발

### ISSUE THREAD

**Issue by woochang0110** [yg-park/EOF_SeparateTrashCollection#2]
통신 객체 TCP, UDP가 합쳐진 Comm 클래스 개발

**Comment by woochang0110** [comment]
라즈베리용 카메라 호환

**Comment by woochang0110** [comment]
UDP 서버 측 수신 이후 GUI picture control에 연계

**Comment by woochang0110** [comment]
UDP 서버-클라이언트 실시간 라즈베리용 카메라 출력 통신 및 jpg 형태 파일로 저장 구현 완료

**Comment by woochang0110** [comment]
UDP 서버측 수신 이미지 저장하지 않고 바로 MFC GUI에 출력하기 위한 변수형태로 저장하는 Format 고민중 .... 1. MFC에서 지원하는 CImage 2. OpenCV에서 지원하는 cv::Mat

**Comment by woochang0110** [comment]
opencv 라이브러리 사용 없이 MFC에서 지원하는 CImage로 처리하기로 @DohyeonP 와 결정

**Comment by kenGwon** [comment]
팀원 우창민이 중국에 간 관계로 팀원 권강현이 대신 풀리퀘스트 생성후 병합
