### ISSUE TITLE
클라이언트-서버간 송수신 되는 오디오 파일의 크기가 너무 큰 것 같습니다.

### ISSUE THREAD

**Issue by kenGwon** [yg-park/EOF_SeparateTrashCollection#47]
5초 분량의 오디오를 보내는데, 압축되지 않은 높은 bit rate의 음원이 전송되어, 전송시간이 좀 길게 걸리는것 같습니다.
오디오 파일을 압축하고, bit rate를 줄이는 등의 방법을 고려해봐야 할 것 같습니다.

**Comment by woochang0110** [comment]
확인해보니 전송시간이 길게 소요되는 원인은 Main_GUI.py 내에 audio thread에 있는 time.sleep(5) 때문이었던걸로 확인되었습니다.
현재 녹음 후 0.2초내에 서버측에서 수신 가능합니다. bit rate를 줄이거나 하는 식의 작업은 음질에 영향을 미치기 때문에 whisper 입력 등에 영향을 미칠거 같습니다. 따라서 음질 샘플링 파라미터는 현상 유지 하겠습니다.

**Comment by kenGwon** [comment]
@woochang0110 아 넵, 그럼 해당 변경사항 다음 PR에 적용해주세요!
